import type {
  ProtocolDraft,
  ProtocolSection,
  SAPPlan,
  SampleSizeResult,
  StudySpec,
} from "./types";

const REQUIRED_SECTIONS: { id: string; title: string; template: (spec: StudySpec) => string }[] = [
  {
    id: "background-rationale",
    title: "Background & Rationale",
    template: (spec) =>
      `Summarise current evidence for ${spec.condition ?? "the condition"} in ${
        spec.populationDescription ?? "the intended population"
      } and justify the need for this study in the stated setting.`,
  },
  {
    id: "objectives",
    title: "Objectives",
    template: (spec) =>
      `List primary and secondary objectives. Ensure the primary objective is aligned with ${
        spec.primaryEndpoint?.name ?? "the confirmed primary endpoint"
      }.`,
  },
  {
    id: "study-design",
    title: "Study Design",
    template: (spec) =>
      `Describe the ${spec.designLabel ?? "proposed"} (${spec.designId ?? "design TBD"}) design, including observational/interventional classification, overall flow, and setting (${spec.setting ?? "setting pending"}).`,
  },
  {
    id: "population-eligibility",
    title: "Study Population & Eligibility",
    template: (spec) =>
      `Detail inclusion and exclusion criteria for ${
        spec.populationDescription ?? "the intended participants"
      }, referencing recruitment sources and screening approach.`,
  },
  {
    id: "study-procedures",
    title: "Study Procedures & Visit Schedule",
    template: (spec) =>
      `Outline study visits, procedures, data collection time points, and handling of protocol deviations. ${
        spec.visitScheduleSummary ?? "Provide visit timing aligned with endpoints."
      }`,
  },
  {
    id: "endpoints",
    title: "Endpoints & Outcome Measures",
    template: (spec) =>
      `Enumerate all endpoints. Confirm the primary endpoint ${
        spec.primaryEndpoint?.name ?? "[to be defined]"
      } with measurement definition, timeframe ${spec.primaryEndpoint?.timeframe ?? "[specify]"}, and data source.`,
  },
  {
    id: "sample-size",
    title: "Sample Size & Justification",
    template: () =>
      "Insert deterministic sample size assumptions, formulas, and resulting numbers. Document data sources for assumptions and any design effect or dropout adjustments.",
  },
  {
    id: "statistical-analysis",
    title: "Statistical Analysis Overview",
    template: () =>
      "Summarise primary and secondary analyses referencing the SAP. Include analysis sets, models, effect measures, and planned sensitivity analyses.",
  },
  {
    id: "safety-monitoring",
    title: "Safety Monitoring & AE/SAE Reporting",
    template: () =>
      "Describe AE/SAE collection, reporting timelines, responsibilities, and escalation pathways consistent with Indian GCP/ICMR expectations.",
  },
  {
    id: "data-management",
    title: "Data Management & Confidentiality",
    template: () =>
      "Detail eCRF processes, data validation, quality control, monitoring, and compliance with ALCOA+ principles and local privacy requirements.",
  },
  {
    id: "ethics-regulatory",
    title: "Ethics & Regulatory Considerations",
    template: () =>
      "Summarise IEC submission requirements, CTRI registration intent, insurance/compensation references, without implying approvals or registrations.",
  },
  {
    id: "consent-process",
    title: "Informed Consent Process",
    template: () =>
      "Describe consent/assent procedures, languages, documentation, audio-visual requirements (if any), and process for vulnerable participants.",
  },
  {
    id: "compensation",
    title: "Compensation & Medical Care for Injury",
    template: () =>
      "State approach to compensation and medical management for study-related injury referencing sponsor or institutional policy (PI to confirm).",
  },
  {
    id: "publication",
    title: "Publication, Data Sharing & Archiving",
    template: () =>
      "Outline dissemination plans, authorship considerations, data sharing governance, and record retention per regulations.",
  },
  {
    id: "closing-reminder",
    title: "Draft Status Notice",
    template: () =>
      "Draft generated by Aurora Research OS based on supplied inputs. Requires review and approval by Principal Investigator and Ethics Committee. Not a legal or regulatory approval.",
  },
];

export function buildProtocolDraft(
  studySpec: StudySpec,
  sap: SAPPlan,
  sampleSize: SampleSizeResult
): ProtocolDraft {
  const warnings: string[] = [];

  if (!studySpec.title?.trim()) {
    warnings.push("Study title is missing; protocol draft incomplete.");
  }
  if (!studySpec.designId) {
    warnings.push("Study design not finalised; confirm design classification.");
  }
  if (!studySpec.primaryEndpoint) {
    warnings.push("Primary endpoint missing; objectives and analyses need PI input.");
  }
  if (sampleSize.status !== "ok") {
    warnings.push("Sample size justification pending; include final numbers before submission.");
  }
  if (sap.endpoints.length === 0) {
    warnings.push("SAP does not list any endpoints; confirm with statistician.");
  }

  const sections: ProtocolSection[] = REQUIRED_SECTIONS.map((section) => ({
    id: section.id,
    title: section.title,
    required: true,
    content: section.template(studySpec),
  }));

  return {
    title: studySpec.title,
    shortTitle: studySpec.title?.slice(0, 80),
    versionTag: "Draft v1.0",
    sections,
    warnings,
  };
}

