export type SampleSizeAssumptionsBase = Record<string, unknown>;
export type BaselineBuildResult = Record<string, any>;
export type RegistryFieldMapping = Record<string, any>;
export type ValidationIssue = Record<string, any>;

const BASELINE: BaselineBuildResult = {
  studySpec: {
    title: "Stub Protocol for Testing",
    designLabel: "Two-arm randomized trial",
    primaryEndpoint: { name: "30-day mortality", type: "binary" },
  },
  protocol: {
    title: "Stub Protocol",
    versionTag: "v0-test",
    sections: [
      { id: "background", title: "Background", required: true, content: "Testing background." },
      { id: "objectives", title: "Objectives", required: true, content: "Primary objective placeholder." },
    ],
    warnings: [],
  },
  sap: {
    analysisSets: { fullAnalysisSet: "All randomized participants." },
    endpoints: [
      {
        endpointName: "30-day mortality",
        role: "primary",
        type: "binary",
        testOrModel: "Chi-square test",
        effectMeasure: "Risk ratio",
      },
    ],
    multiplicity: "Single primary endpoint at alpha 0.05.",
    interimAnalysis: "None planned for stub.",
    subgroupAnalyses: "Exploratory only.",
    sensitivityAnalyses: "Not planned in stub.",
    missingDataGeneral: "Complete case analysis for stub.",
    software: "R or Python",
    warnings: [],
  },
  crf: {
    forms: [
      {
        id: "baseline",
        name: "Baseline Form",
        purpose: "baseline",
        fields: [
          {
            id: "subject_id",
            label: "Subject ID",
            type: "text",
            required: true,
            isCore: true,
          },
          {
            id: "mortality",
            label: "30-day mortality",
            type: "select",
            required: true,
            isCore: true,
            mapsToEndpointName: "30-day mortality",
            options: ["Yes", "No"],
          },
        ],
      },
    ],
    warnings: [],
  },
  pisIcf: {
    sections: [
      { id: "intro", title: "Introduction", required: true, content: "Stub intro." },
      { id: "purpose", title: "Purpose", required: true, content: "Stub purpose." },
      { id: "risks", title: "Risks", required: true, content: "Stub risks." },
      { id: "benefits", title: "Benefits", required: true, content: "Stub benefits." },
      {
        id: "confidentiality",
        title: "Confidentiality",
        required: true,
        content: "Stub confidentiality statement.",
      },
      {
        id: "voluntary_right_to_withdraw",
        title: "Voluntary Participation",
        required: true,
        content: "Participation is voluntary in stub.",
      },
      {
        id: "contacts",
        title: "Contacts",
        required: true,
        content: "Contact the PI for questions.",
      },
      {
        id: "compensation_injury",
        title: "Compensation",
        required: true,
        content: "Compensation handled per institutional policy.",
      },
      { id: "procedures", title: "Procedures", required: true, content: "Stub procedures." },
      { id: "alternatives", title: "Alternatives", required: true, content: "Stub alternatives." },
      { id: "data_use_future", title: "Future Use", required: false, content: "Future use optional." },
    ],
    warnings: [],
  },
  iecCoverNote: {
    title: "Stub IEC Note",
    summary: "Stub summary.",
    designAndMethods: "Randomized stub.",
    riskBenefit: "Minimal risk.",
    keyEthicsHighlights: "Consent captured.",
    attachmentsList: ["Protocol", "SAP", "PIS/ICF", "CRF"],
    warnings: [],
  },
  regulatoryChecklist: {
    items: [
      { id: "design", label: "Design supported", scope: "design", status: "ok", severity: "info" },
      {
        id: "endpoint",
        label: "Primary endpoint documented",
        scope: "endpoints",
        status: "ok",
        severity: "info",
      },
    ],
  },
  registryMapping: {
    registry: "CTRI-like",
    fields: [
      {
        fieldId: "ctri_public_title",
        label: "Public Title",
        value: "Stub public title",
        source: "auto",
      },
    ],
  },
  literaturePlan: {
    picoSummary: "Adults undergoing emergency laparotomy vs standard care.",
    suggestedKeywords: ["emergency laparotomy", "mortality", "randomized"],
    notes: ["Conduct formal database searches."],
  },
  sampleSize: {
    status: "ok",
    assumptions: {},
    warnings: [],
    notes: [],
  },
  sapExplanation: {
    sampleSizeSummary: "Sample size derived from stub assumptions.",
    analysisSummary: "Stub analysis summary.",
    assumptionSummary: "Stub assumption summary.",
    caveats: ["Stub caveat."],
  },
  issues: [],
  disclaimer: "Draft generated by stub module.",
  versionInfo: {
    rulebookProfile: "test-profile",
    rulebookVersion: "1.0.0",
    generatedAt: "2024-01-01T00:00:00.000Z",
  },
};

export function buildBaselinePackageFromIdea(
  _idea: string,
  _assumptions?: Partial<SampleSizeAssumptionsBase>
): BaselineBuildResult {
  return JSON.parse(JSON.stringify(BASELINE));
}
